base_url = "https://jane-212.github.io"
title = "Jane's Blog"
theme = "paper"

generate_feed = true

taxonomies = [{ name = "tags", paginate_by = 5 }]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author = "Jane"
author_url = "https://github.com/jane-212"
countly = { enabled = true, key = "1db43d602c430f0fcc0e9f18d63c38a78c9e5c6b" }
