base_url = "https://jane-212.github.io"

compile_sass = true

title = "Blog"

theme = "after-dark"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
author = "jane"

after_dark_title = "Blog"

after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
