base_url = "/"
title = "Jane's Blog"
description = "This is Jane's Blog, share about coding and daily."
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
]

[extra]
author = "Jane"
display_author = true
favicon = "favicon.ico"
twitter_card = true
header_nav = [
  { url = "/", name = "/首页/" },
  { url = "/blog/", name = "/博客/" },
  { url = "/about/", name = "/关于/" },
]
