base_url = "https://jane-212.github.io"
title = "Jane's Blog"
theme = "anemone"

generate_feed = true
feed_filename = "rss.xml"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
author = "Jane"
display_author = true

favicon = "favicon.ico"

default_theme = "light"
list_pages = true
twitter_card = true
toc = true

header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/blog", name_en = "/blog/" },
    { url = "/about", name_en = "/about/" },
]
